name: Deploy on Ubuntu Server

on:
  push:
    branches:
      - dev-deployment
  
jobs:
  # Job 1: Build and Push Docker Image
  build-and-push:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      # 3. Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/${{secrets.APP_NAME}}:latest .

      # 4. Push Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.APP_NAME}}:latest

  # Job 2: Deploy to Ubuntu Server
  deploy:
    name: Deploy to Ubuntu Server
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      # 1. Set up SSH to access the server
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

      # 2. Pull and run Docker image on the server
      - name: Deploy on Ubuntu Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SERVER_IP}} << "EOF"
          docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.APP_NAME}}:latest
          docker stop ${{secrets.APP_NAME}} || true
          docker rm ${{secrets.APP_NAME}} || true
          docker run -d --name ${{ secrets.APP_NAME }} -p ${{ secrets.APP_PORT }}:80 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}
          EOF
